"""Repository 接口——只操作领域模型，不暴露 dict/ORM."""

from typing import Protocol

from ..domain import PC, Actor


class CharacterRepo(Protocol):
    """角色仓储——操作 PC/Actor 领域实体."""

    async def save_pc(self, pc: PC) -> None: ...
    async def save_actor(self, actor: Actor) -> None: ...
    async def find_pc(self, character_id: str) -> PC | None: ...
    async def find_actor(self, character_id: str) -> Actor | None: ...
    async def find_all_pcs(self) -> list[PC]: ...
    async def find_all_actors(self) -> list[Actor]: ...
