--  ============================================================
--  AIGameWorld SQLite Schema / 数据库表结构定义
--  WAL 模式：支持并发读 + 单写 / WAL mode: concurrent reads + single write
--  ============================================================

PRAGMA journal_mode=WAL;
PRAGMA foreign_keys=ON;

-- ============================================================
--  worlds: 世界 / Worlds
-- ============================================================
CREATE TABLE IF NOT EXISTS worlds (
    id              TEXT PRIMARY KEY,
    name            TEXT NOT NULL,
    description     TEXT NOT NULL DEFAULT '',
    version         TEXT NOT NULL DEFAULT '1.0.0',
    rule_set        TEXT NOT NULL DEFAULT 'dnd_5e_srd',
    author          TEXT NOT NULL DEFAULT '',
    starting_scene_id TEXT NOT NULL DEFAULT '',  -- world 关联初始场景 / world-associated starting scene
    current_scene_id TEXT NOT NULL DEFAULT '',   -- 当前主场景（world_init 写入 / party.decide_scene 更新）/ current main scene
    status          TEXT NOT NULL DEFAULT 'init', -- 初始化状态：init -> ready（world_init 守卫）/ init status guard

    data_tick       INTEGER NOT NULL DEFAULT 0,  -- 后端已生成的数据 tick / Latest data tick generated by backend
    display_tick    INTEGER NOT NULL DEFAULT 0,  -- 前端已展示到的 tick / Latest tick presented to frontend
    ext_json        TEXT NOT NULL DEFAULT '{}',
    created_at      TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    updated_at      TEXT NOT NULL DEFAULT (datetime('now', 'localtime'))
);

-- ============================================================
--  player_characters: 主角团 / Player Characters
-- ============================================================
CREATE TABLE IF NOT EXISTS player_characters (
    id                  TEXT PRIMARY KEY,
    name                TEXT NOT NULL,
    role                TEXT NOT NULL,
    race                TEXT,
    status              TEXT NOT NULL DEFAULT 'active',
    scene_id            TEXT NOT NULL,
    position_x          INTEGER NOT NULL DEFAULT 0,
    position_y          INTEGER NOT NULL DEFAULT 0,
    attributes_json     TEXT NOT NULL,
    combat_json         TEXT NOT NULL,
    arc_json            TEXT NOT NULL,
    long_term_goal      TEXT,
    values_json         TEXT NOT NULL DEFAULT '[]',
    personality         TEXT,
    equipment_json      TEXT NOT NULL DEFAULT '{}',
    inventory_json      TEXT NOT NULL DEFAULT '[]',
    memory_count            INTEGER NOT NULL DEFAULT 0,
    importance_accumulator  REAL NOT NULL DEFAULT 0,
    relationships_json      TEXT NOT NULL DEFAULT '{}',
    joined_tick         INTEGER NOT NULL DEFAULT 0,
    roster_status       TEXT NOT NULL DEFAULT 'member',
    world_id            TEXT NOT NULL DEFAULT '',
    ext_json            TEXT NOT NULL DEFAULT '{}',
    created_at          TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    updated_at          TEXT NOT NULL DEFAULT (datetime('now', 'localtime'))
);

-- ============================================================
--  actors: 配角 / Actors
-- ============================================================
CREATE TABLE IF NOT EXISTS actors (
    id          TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    role        TEXT,
    race        TEXT,
    status      TEXT NOT NULL DEFAULT 'active',
    disposition TEXT NOT NULL DEFAULT 'neutral',
    scene_id    TEXT NOT NULL,
    position_x  INTEGER NOT NULL DEFAULT 0,
    position_y  INTEGER NOT NULL DEFAULT 0,
    attributes_json TEXT NOT NULL,
    combat_json     TEXT,
    personality         TEXT,
    functions_json      TEXT NOT NULL DEFAULT '[]',
    function_data_json  TEXT NOT NULL DEFAULT '{}',
    equipment_json  TEXT,
    inventory_json  TEXT NOT NULL DEFAULT '[]',
    memory_count            INTEGER NOT NULL DEFAULT 0,
    importance_accumulator  REAL NOT NULL DEFAULT 0,
    relationships_json      TEXT NOT NULL DEFAULT '{}',
    dm_assigned         INTEGER NOT NULL DEFAULT 0,
    motivation_injected TEXT,
    world_id            TEXT NOT NULL DEFAULT '',
    ext_json            TEXT NOT NULL DEFAULT '{}',
    created_at  TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    updated_at  TEXT NOT NULL DEFAULT (datetime('now', 'localtime'))
);

-- ============================================================
--  scenes: 场景定义 / Scene definitions
-- ============================================================
CREATE TABLE IF NOT EXISTS scenes (
    id              TEXT PRIMARY KEY,
    name            TEXT NOT NULL,
    type            TEXT NOT NULL,
    description     TEXT,
    spawn_x         INTEGER NOT NULL DEFAULT 0,
    spawn_y         INTEGER NOT NULL DEFAULT 0,
    map_width       INTEGER NOT NULL DEFAULT 40,
    map_height      INTEGER NOT NULL DEFAULT 40,
    world_id        TEXT NOT NULL,
    tilemap_summary TEXT,
    ext_json        TEXT NOT NULL DEFAULT '{}',
    created_at      TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    updated_at      TEXT NOT NULL DEFAULT (datetime('now', 'localtime'))
);

-- ============================================================
--  items: 物品全局定义 / Global item definitions
-- ============================================================
CREATE TABLE IF NOT EXISTS items (
    id          TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    item_type   TEXT NOT NULL,
    rarity      TEXT NOT NULL DEFAULT 'common',
    weight      REAL NOT NULL DEFAULT 0,
    value       INTEGER NOT NULL DEFAULT 0,
    description TEXT,
    data        TEXT NOT NULL DEFAULT '{}',
    world_id    TEXT NOT NULL,
    ext_json    TEXT NOT NULL DEFAULT '{}',
    created_at  TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    updated_at  TEXT NOT NULL DEFAULT (datetime('now', 'localtime'))
);

-- ============================================================
--  scene_objects: 场景物体 / Scene objects
-- ============================================================
CREATE TABLE IF NOT EXISTS scene_objects (
    id                  TEXT PRIMARY KEY,
    name                TEXT NOT NULL,
    object_type         TEXT NOT NULL,
    scene_id            TEXT NOT NULL,
    position_x          INTEGER NOT NULL DEFAULT 0,
    position_y          INTEGER NOT NULL DEFAULT 0,
    interactable        INTEGER NOT NULL DEFAULT 1,
    interact_data       TEXT,
    world_id            TEXT NOT NULL DEFAULT '',
    ext_json            TEXT NOT NULL DEFAULT '{}',
    created_at          TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    updated_at          TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    FOREIGN KEY (scene_id) REFERENCES scenes(id)
);
CREATE INDEX IF NOT EXISTS idx_scene_objects_scene ON scene_objects(scene_id);


-- ============================================================
--  tick_events: tick 事件明细 / Tick event details
-- ============================================================
CREATE TABLE IF NOT EXISTS tick_events (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    tick            INTEGER NOT NULL,
    type            TEXT    NOT NULL,
    payload         TEXT    NOT NULL,
    world_id        TEXT    NOT NULL DEFAULT '',
    ext_json        TEXT    NOT NULL DEFAULT '{}',
    created_at      TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),
    updated_at      TEXT    NOT NULL DEFAULT (datetime('now', 'localtime'))
);
CREATE INDEX IF NOT EXISTS idx_tick_events_world_tick ON tick_events(world_id, tick);



-- ============================================================
--  dm_records: DM 产出记录 / DM output records
-- ============================================================
CREATE TABLE IF NOT EXISTS dm_records (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    world_id        TEXT NOT NULL,
    tick            INTEGER NOT NULL,
    plot_brief      TEXT NOT NULL DEFAULT '',
    hint_list       TEXT NOT NULL DEFAULT '[]',
    dm_narrative    TEXT NOT NULL DEFAULT '',
    ext_json        TEXT NOT NULL DEFAULT '{}',
    created_at      TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    updated_at      TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    UNIQUE(world_id, tick)
);
CREATE INDEX IF NOT EXISTS idx_dm_records_world_tick ON dm_records(world_id, tick);

-- ============================================================
--  story_summaries: 故事摘要 / Story summaries
-- ============================================================
CREATE TABLE IF NOT EXISTS story_summaries (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    world_id        TEXT NOT NULL,
    tick_start      INTEGER NOT NULL,
    tick_end        INTEGER NOT NULL,
    summary         TEXT NOT NULL,
    summary_type    TEXT NOT NULL DEFAULT 'narrative',
    ext_json        TEXT NOT NULL DEFAULT '{}',
    created_at      TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    updated_at      TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),
    UNIQUE(world_id, tick_start, summary_type)
);
CREATE INDEX IF NOT EXISTS idx_summaries_world ON story_summaries(world_id);

-- ============================================================
--  memories: 角色/世界记忆（中期记忆）/ Character/world memories (mid-term)
-- ============================================================
CREATE TABLE IF NOT EXISTS memories (
    id              TEXT PRIMARY KEY,
    pc_id           TEXT    NOT NULL,
    content         TEXT    NOT NULL,
    tick            INTEGER NOT NULL DEFAULT 0,
    importance      INTEGER NOT NULL DEFAULT 2,
    memory_type     TEXT    NOT NULL DEFAULT 'observation',
    period          TEXT    NOT NULL DEFAULT 'medium_term',
    entity_type     TEXT    NOT NULL DEFAULT 'pc',
    world_id        TEXT    NOT NULL DEFAULT '',
    ext_json        TEXT    NOT NULL DEFAULT '{}',
    created_at      TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),
    updated_at      TEXT    NOT NULL DEFAULT (datetime('now', 'localtime'))
);
CREATE INDEX IF NOT EXISTS idx_memories_pc_tick ON memories(pc_id, tick);
CREATE INDEX IF NOT EXISTS idx_memories_world ON memories(world_id);
CREATE INDEX IF NOT EXISTS idx_memories_type ON memories(memory_type);
CREATE INDEX IF NOT EXISTS idx_memories_period ON memories(period);

-- ============================================================
--  tick_metrics: tick 运行指标 / Tick runtime metrics
-- ============================================================
CREATE TABLE IF NOT EXISTS tick_metrics (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    tick              INTEGER NOT NULL,
    world_id          TEXT    NOT NULL,
    latency_ms        REAL    NOT NULL DEFAULT 0,
    llm_calls         INTEGER NOT NULL DEFAULT 0,
    tokens_in         INTEGER NOT NULL DEFAULT 0,
    tokens_out        INTEGER NOT NULL DEFAULT 0,
    events_count      INTEGER NOT NULL DEFAULT 0,
    estimated_cost_usd REAL   NOT NULL DEFAULT 0,
    model             TEXT    NOT NULL DEFAULT '',
    created_at        TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),
    updated_at        TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),
    UNIQUE(tick, world_id)
);
CREATE INDEX IF NOT EXISTS idx_tick_metrics_world ON tick_metrics(world_id);

-- ============================================================
--  eval_results: 评估结果 / Evaluation results
-- ============================================================
CREATE TABLE IF NOT EXISTS eval_results (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    dataset    TEXT    NOT NULL,
    case_id    TEXT    NOT NULL,
    dimension  TEXT    NOT NULL,
    score      REAL    NOT NULL,
    reason     TEXT    DEFAULT '',
    improvement TEXT    DEFAULT '',
    l1_checks  TEXT    DEFAULT '{}',
    created_at TEXT    NOT NULL DEFAULT (datetime('now', 'localtime')),
    updated_at TEXT    NOT NULL DEFAULT (datetime('now', 'localtime'))
);
CREATE INDEX IF NOT EXISTS idx_eval_dataset ON eval_results(dataset);
CREATE INDEX IF NOT EXISTS idx_eval_dimension ON eval_results(dimension);
